### Send otp code
GET http://localhost/api/v1/otp?phone=77776182855

### Check OTP code
POST http://localhost/api/v1/otp
Content-Type: application/json

{
    "key": "2a9d22ed-9f76-4bd2-9a6d-9f13716e943a",
    "otp": "4445"
  }