### Send otp code
GET http://localhost/api/v1/otp?phone=77776182855

### Check OTP code
POST http://localhost/api/v1/otp
Content-Type: application/json

{
    "key": "79946cd4-3fd1-4be1-9a2f-cdccd8ad5086",
    "otp": "4699"
  }